# This is a basic workflow to help you get started with Actions

name: dev workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    strategy:
      matrix:
        # python-versions: [ "3.7", "3.8", "3.9", "3.10", "3.11"]
        python-versions: [ "3.9"]
        # os: [ubuntu-18.04, macos-latest, windows-latest]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt

      - name: test with unittest/pytest
        run:
          make unittest

      - name: coverage with pytest-cov
        run:
          make coverage

  docs:
    strategy:
      matrix:
        # python-versions: [ "3.7", "3.8", "3.9", "3.10", "3.11"]
        python-versions: [ "3.9"]
        # os: [ubuntu-18.04, macos-latest, windows-latest]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: build documentation
        run: |
          cd docs
          make html

      - name: publish documentation
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0.0
        with:
          branch: main
          dir_docs: docs
          # sphinxapiopts: '--separate -o . # ../'
          # sphinxapiexclude: '../*setup* ../*.ipynb'
          # sphinxopts: ''
    # needs: test
